#!/bin/sh

setup()
{
    echo '  ______                       __               ______                                 __ '
    echo ' /      \                     /  |             /      \                               /  |'
    echo '/$$$$$$  |  ______    _______ $$ |____        /$$$$$$  | _______    ______    ______  $$ |'
    echo '$$ |__$$ | /      \  /       |$$      \       $$ |__$$ |/       \  /      \  /      \ $$ |'
    echo '$$    $$ |/$$$$$$  |/$$$$$$$/ $$$$$$$  |      $$    $$ |$$$$$$$  |/$$$$$$  |/$$$$$$  |$$ |'
    echo '$$$$$$$$ |$$ |  $$/ $$ |      $$ |  $$ |      $$$$$$$$ |$$ |  $$ |$$ |  $$ |$$    $$ |$$ |'
    echo '$$ |  $$ |$$ |      $$ \_____ $$ |  $$ |      $$ |  $$ |$$ |  $$ |$$ \__$$ |$$$$$$$$/ $$ |'
    echo '$$ |  $$ |$$ |      $$       |$$ |  $$ |      $$ |  $$ |$$ |  $$ |$$    $$ |$$       |$$ |'
    echo '$$/   $$/ $$/        $$$$$$$/ $$/   $$/       $$/   $$/ $$/   $$/  $$$$$$$ | $$$$$$$/ $$/ '
    echo '                                                                  /  \__$$ |              '
    echo '                                                                  $$    $$/               '
    echo -e '                                                                   $$$$$$/                \n'

    archangelmenu
}

archangelmenu()
{
    echo -e " Key            Menu Option              Description"
    echo -e "-----   ----------------------------  -----------------"
    echo -e " [1]  -  Suckless Software            (angelpilled's pre-configured suckless softwares)"
    echo -e " [2]  -  Dev's Favorites              (angelpilled's favorite softwares)"
    echo -e " [3]  -  Cybersec Tools               (Install the top 10 most used cybersecurity tools.)"
    echo -e " [4]  -  Scientist's Tools            (Installs the best scientific software)"
    echo -e " [5]  -  Desktop Environments         (Install DEs like KDE, XFCE4, Gnome, etc.)"

    echo -e
    echo -e " Key            Standalone               Description"
    echo -e "-----   ----------------------------  -----------------"
    echo -e " [A]  -  Install Arch Linux           (Install Arch Linux with a simple and quick script!)"

    echo -e ""
    read -n1 -p "Please select an option from the list: " menuinput
    echo -e
    optionsList
}

optionsList()
{
case $menuinput in
      1) install_suckless;;
      2) install_favorites;;
      3) install_cybersec;;
      4) install_de;;

      a|A) install_arch;;

      x|X|q|Q) echo -e "\nSee you next time!";;
    esac
}

install_suckless()
{
    echo -e "This function will install angelpilled's pre-configured suckless software pack.\n"
    echo "The pack contains: dwm, dmenu, slstatus, st, slock, surf\n"

    read -n1 -p "Proceed to continue? (y/n) " answer; echo -e
    case $answer in
	[yY])
	    echo -e "Installing suckless software...\n"

	    sudo pacman -S --needed --noconfirm make gcc webkit2gtk gcr libavif
	    cd ~
	    yay -S --needed --noconfirm ttf-iosevka ttf-font-awesome
	    git init angel-suckless
	    cd angel-suckless
	    git remote add origin https://github.com/angelpilled/angelpilled-configs
	    git sparse-checkout init --cone
	    git sparse-checkout set suckless
	    git pull origin master
	    cd suckless
	    ./build.sh
	    cd ~ && echo -e "Arch Angel: suckless software installation is now finished."
	    ;;
	[nN])
	    echo -e "Exiting to main menu.\n"
	    archangelmenu
	    ;;
    esac
}

install_favorites()
{
    read -n1 -p "angelpilled's favorite softwares will be installed now. Do you wish to proceed? (y/n) " answer
    echo -e
    case $answer in
	[Yy])
	    sudo pacman -S --needed --noconfirm neofetch tmux terminus-font cmus firefox alsa-utils pulseaudio-alsa gnome-themes-extra lxappearance cowsay fortune-mod xorg xorg-xinit vlc thunar tumbler ntfs-3g npm luajit maim xbindkeys htop arandr filezilla gimp picom feh python unzip xclip neovim

	    ls /usr/bin/yay &> /dev/null
	    if [ $? -ne 0 ]; then
		cd ~ && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
	    fi

	    ;;
	[nN])
	    echo -e "\nExiting to main menu.\n"
	    archangelmenu
	    ;;
    esac
}

install_cybersec()
{
    echo -e "Install Cybersecurity Tools option selected"

    echo "Downloading cybersecurity tools from the Official Arch Repository."
	sudo pacman -S --needed --noconfirm nmap wireshark-cli metasploit aircrack-ng john hydra sqlmap nikto hashcat

    echo "Installing AUR packages."
	yay -S --needed --noconfirm burpsuite
}

install_scientific()
{
    # WORK IN PROGRESS !!!!!
    read -n1 -p "Scientific software will be installed. Do you wish to proceed? (y/n) " answer
    case $answer in
	[yY])
	    echo "Yaay!"
	    ;;
	[nN])
	    echo "Naa!"
	    ;;
    esac
}

install_de()
{
    # WORK IN PROGRESS !!!!!
    echo -e "Installing DEs..." 
}

install_arch()
{
    echo "Installing Arch Linux...\n"
}

setup
